version: "3"
services:
  mongo:
    image: mongo
    volumes:
      - ./dbdata:/data/db
    ports:
      - "27017:27017"
  web:
    build: .
    command: npm run dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      DB_CONNECTION: mongodb://localhost:27017
